version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_DATABASE: book_review
      MYSQL_PASSWORD: passw0rd
      MYSQL_ROOT_PASSWORD: passw0rd
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
  api:
    container_name: api
    platform: linux/x86_64
    build:
      context: .
      dockerfile: cmd/go-book-review/Dockerfile
    ports:
      - "8080:8080"
    tty: true
    env_file:
      - ./.env
    depends_on:
      - db
